apiVersion: v1
kind: Pod
metadata:
  labels:
    app: no-db
  name: fastapi-hello-world
spec:
  containers:
    - image: codingkarma/fastapi-hello-world:nodb
      name: fastapi-hello-world
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
